version: '3.8'

services:
  angular:
    build: ./angular
    ports:
      - '8080:80'
    depends_on:
      - api
    restart: always

  api:
    build: ./webapi
    ports:
      - '5001:5001'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./webapi/https/aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: always
